# Generated by Django 4.2 on 2025-06-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=100)),
                ('metier', models.CharField(choices=[('Plombier', 'Plombier'), ('Électricien', 'Électricien'), ('Menuisier', 'Menuisier'), ('Maçon', 'Maçon'), ('Peintre', 'Peintre')], max_length=50)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='artisan_photos/')),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
    ]
