# Generated by Django 4.2 on 2025-06-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaireapp', '0003_remove_artisan_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='experience',
        ),
        migrations.AddField(
            model_name='artisan',
            name='date_debut_activite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
