# Generated by Django 4.2 on 2025-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaireapp', '0004_remove_artisan_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='artisan',
            name='nouveau_metier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='metier',
            field=models.CharField(choices=[('Plombier', 'Plombier'), ('Électricien', 'Électricien'), ('Menuisier', 'Menuisier'), ('Maçon', 'Maçon'), ('Peintre', 'Peintre'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='artisans_photos/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
