# Generated by Django 4.2 on 2025-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaireapp', '0005_remove_artisan_mot_de_passe_artisan_nouveau_metier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='password',
            field=models.CharField(default='motdepasse_temporaire', max_length=255),
        ),
    ]
