# Generated by Django 4.2 on 2025-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaireapp', '0006_artisan_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
