# Generated by Django 4.2 on 2025-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaireapp', '0007_alter_artisan_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='date_debut_activite',
        ),
        migrations.AddField(
            model_name='artisan',
            name='annee_debut_activite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Année de début d'activité"),
        ),
    ]
