# Generated by Django 4.2 on 2025-06-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaireapp', '0008_remove_artisan_date_debut_activite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='annee_debut_activite',
        ),
        migrations.AddField(
            model_name='artisan',
            name='date_debut_activite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
