# Generated by Django 4.2 on 2025-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaireapp', '0009_remove_artisan_annee_debut_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='profil_complet',
            field=models.BooleanField(default=False),
        ),
    ]
